# Generated by Django 3.0.6 on 2020-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('busStop', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('message', models.TextField()),
            ],
        ),
    ]
