# Generated by Django 3.0.6 on 2020-06-04 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingspace',
            old_name='message',
            new_name='message_form',
        ),
    ]
