# Generated by Django 3.0.8 on 2020-09-19 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_auto_20200604_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingspace',
            old_name='message_form',
            new_name='message',
        ),
    ]
