# Generated by Django 3.0.8 on 2020-09-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_set_frequently_asked_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='fourImageGallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file_name', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'verbose_name_plural': '[Gallary] Four Image Gallary',
            },
        ),
    ]
